### ISSUE TITLE
Scroll to top doesn't work within the app after integration Hoko SDK.

### ISSUE THREAD

**Issue by AlexeySergienko** [hoko/hoko-ios#29]
Hello,

We have faced an issue with "scroll to top" functionality after integration Hoko SDK. After some debugging we found that issue related with deferred deeplinking. SFSafariViewController is never releasing.

Could you please check this out?

Thanks in advance,
Best regards,
Alexey

**Comment by hugocore** [comment]
Hi @AlexeySergienko,

Thank you for reporting this issue. Can you help us out here and check if the bugfix at #30 fixes it?

Remove our pod, and link the source code present at this branch instead:
1. Edit your `Podfile` and remove the `pod 'Hoko'` line
2. Run `pod update` to update your local pod repository
3. Open your Xcode project and link the SDK source code (it should be a drag-drop thing)

Run your app with this version and check if the issue is not longer present. Also, test if your smart links and deferred smart links (those that drive the user through the app store) continue to work.

To test deferred smart links, uninstall your app and then just deploy/install your app through Xcode, once you reach the App Store.

Let us know how it goes.

**Comment by AlexeySergienko** [comment]
Hi @hugocore,

Thank you for your quick answer. We've checked the version from [rollback-fingerprinting](https://github.com/hoko/hoko-ios/tree/rollback-fingerprinting) branch. For us everything works fine. 

Best regards,
Alexey

**Comment by hugocore** [comment]
Hi again,

We've release v2.5.0 which includes this fix.
Please update your local pod.

Best regards,
Hugo
